name:                path-extensions
version:             0.0.1.0
license:             BSD3
author:              "Daniel Firth"
maintainer:          "dan.firth@homotopic.tech"
copyright:           "2020 Daniel Firth"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Enumeration of common filetype extensions for use with the path library.
category:            Filesystem

description:         Enumeration of common filetype extensions for use with the path library, add variants for adding an extension to a path and with variants for replacing an existing extension.

dependencies:
- base >= 4.7 && < 5
- exceptions
- path

library:
  source-dirs: src
